name: Deploy Docs Caller

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  call-shared:
    uses: ./.github/workflows/deploy-docs.yml
    with:
      branch: ${{ github.ref_name }}
