name: Deploy Docs Caller

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  call-shared:
    uses: jjainschigg-r/k0rdent-oss-docs/.github/workflows/deploy-docs.yml@main
    with:
      branch: ${{ github.ref_name }}
