name: Deploy Docs Caller

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  call-shared:
    uses: k0rdent/docs/.github/workflows/deploy-docs.yml@main
    with:
      branch: ${{ github.ref_name }}
