name: test release branch trigger

on:
  push:
    branches:
      - 'release-v*'

jobs:
  trace:
    runs-on: ubuntu-latest

    steps:
      - name: Announce trigger success
        run: |
          echo "🎉 This workflow ran on branch: ${{ github.ref }}"
          echo "✅ All good!"
